package com.lantian.lib_base.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lantian.lib_base.entity.module.response.breeds.CountBreedTure;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COUNT_BREED_TURE".
*/
public class CountBreedTureDao extends AbstractDao<CountBreedTure, String> {

    public static final String TABLENAME = "COUNT_BREED_TURE";

    /**
     * Properties of entity CountBreedTure.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Userid = new Property(0, String.class, "userid", true, "USERID");
        public final static Property Status = new Property(1, int.class, "status", false, "STATUS");
        public final static Property Breedcont = new Property(2, String.class, "breedcont", false, "BREEDCONT");
        public final static Property Expenditure = new Property(3, String.class, "expenditure", false, "EXPENDITURE");
    }


    public CountBreedTureDao(DaoConfig config) {
        super(config);
    }
    
    public CountBreedTureDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COUNT_BREED_TURE\" (" + //
                "\"USERID\" TEXT PRIMARY KEY NOT NULL ," + // 0: userid
                "\"STATUS\" INTEGER NOT NULL ," + // 1: status
                "\"BREEDCONT\" TEXT," + // 2: breedcont
                "\"EXPENDITURE\" TEXT);"); // 3: expenditure
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_COUNT_BREED_TURE_USERID_DESC_STATUS_DESC ON \"COUNT_BREED_TURE\"" +
                " (\"USERID\" DESC,\"STATUS\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COUNT_BREED_TURE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CountBreedTure entity) {
        stmt.clearBindings();
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(1, userid);
        }
        stmt.bindLong(2, entity.getStatus());
 
        String breedcont = entity.getBreedcont();
        if (breedcont != null) {
            stmt.bindString(3, breedcont);
        }
 
        String expenditure = entity.getExpenditure();
        if (expenditure != null) {
            stmt.bindString(4, expenditure);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CountBreedTure entity) {
        stmt.clearBindings();
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(1, userid);
        }
        stmt.bindLong(2, entity.getStatus());
 
        String breedcont = entity.getBreedcont();
        if (breedcont != null) {
            stmt.bindString(3, breedcont);
        }
 
        String expenditure = entity.getExpenditure();
        if (expenditure != null) {
            stmt.bindString(4, expenditure);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public CountBreedTure readEntity(Cursor cursor, int offset) {
        CountBreedTure entity = new CountBreedTure( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userid
            cursor.getInt(offset + 1), // status
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // breedcont
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // expenditure
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CountBreedTure entity, int offset) {
        entity.setUserid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStatus(cursor.getInt(offset + 1));
        entity.setBreedcont(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExpenditure(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(CountBreedTure entity, long rowId) {
        return entity.getUserid();
    }
    
    @Override
    public String getKey(CountBreedTure entity) {
        if(entity != null) {
            return entity.getUserid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CountBreedTure entity) {
        return entity.getUserid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
