package com.lantian.lib_base.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lantian.lib_base.entity.module.response.breeds.CountCompensate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COUNT_COMPENSATE".
*/
public class CountCompensateDao extends AbstractDao<CountCompensate, String> {

    public static final String TABLENAME = "COUNT_COMPENSATE";

    /**
     * Properties of entity CountCompensate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Status = new Property(0, int.class, "status", false, "STATUS");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
        public final static Property User_id = new Property(2, String.class, "user_id", true, "USER_ID");
        public final static Property Hukou_id = new Property(3, String.class, "hukou_id", false, "HUKOU_ID");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Price = new Property(5, String.class, "price", false, "PRICE");
        public final static Property Addtime = new Property(6, String.class, "addtime", false, "ADDTIME");
        public final static Property Shenhe = new Property(7, String.class, "shenhe", false, "SHENHE");
    }


    public CountCompensateDao(DaoConfig config) {
        super(config);
    }
    
    public CountCompensateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COUNT_COMPENSATE\" (" + //
                "\"STATUS\" INTEGER NOT NULL ," + // 0: status
                "\"ID\" TEXT," + // 1: id
                "\"USER_ID\" TEXT PRIMARY KEY NOT NULL ," + // 2: user_id
                "\"HUKOU_ID\" TEXT," + // 3: hukou_id
                "\"TITLE\" TEXT," + // 4: title
                "\"PRICE\" TEXT," + // 5: price
                "\"ADDTIME\" TEXT," + // 6: addtime
                "\"SHENHE\" TEXT);"); // 7: shenhe
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_COUNT_COMPENSATE_ID_DESC_STATUS_DESC_USER_ID_DESC ON \"COUNT_COMPENSATE\"" +
                " (\"ID\" DESC,\"STATUS\" DESC,\"USER_ID\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COUNT_COMPENSATE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CountCompensate entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStatus());
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(3, user_id);
        }
 
        String hukou_id = entity.getHukou_id();
        if (hukou_id != null) {
            stmt.bindString(4, hukou_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(6, price);
        }
 
        String addtime = entity.getAddtime();
        if (addtime != null) {
            stmt.bindString(7, addtime);
        }
 
        String shenhe = entity.getShenhe();
        if (shenhe != null) {
            stmt.bindString(8, shenhe);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CountCompensate entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStatus());
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(3, user_id);
        }
 
        String hukou_id = entity.getHukou_id();
        if (hukou_id != null) {
            stmt.bindString(4, hukou_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(6, price);
        }
 
        String addtime = entity.getAddtime();
        if (addtime != null) {
            stmt.bindString(7, addtime);
        }
 
        String shenhe = entity.getShenhe();
        if (shenhe != null) {
            stmt.bindString(8, shenhe);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2);
    }    

    @Override
    public CountCompensate readEntity(Cursor cursor, int offset) {
        CountCompensate entity = new CountCompensate( //
            cursor.getInt(offset + 0), // status
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // user_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // hukou_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // price
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // addtime
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // shenhe
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CountCompensate entity, int offset) {
        entity.setStatus(cursor.getInt(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUser_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHukou_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPrice(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAddtime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setShenhe(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(CountCompensate entity, long rowId) {
        return entity.getUser_id();
    }
    
    @Override
    public String getKey(CountCompensate entity) {
        if(entity != null) {
            return entity.getUser_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CountCompensate entity) {
        return entity.getUser_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
