package com.lantian.lib_base.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lantian.lib_base.entity.module.response.farmer.farmmsg.FarmMsgResponse;
import com.lantian.lib_base.entity.module.response.farmer.farmdatas.FarmSumData;
import com.lantian.lib_base.entity.module.response.product.ProductResponse;
import com.lantian.lib_base.entity.module.response.login.LoginResponse;
import com.lantian.lib_base.entity.module.response.breeds.BreedsList;

import com.lantian.lib_base.database.greendao.FarmMsgResponseDao;
import com.lantian.lib_base.database.greendao.FarmSumDataDao;
import com.lantian.lib_base.database.greendao.ProductResponseDao;
import com.lantian.lib_base.database.greendao.LoginResponseDao;
import com.lantian.lib_base.database.greendao.BreedsListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig farmMsgResponseDaoConfig;
    private final DaoConfig farmSumDataDaoConfig;
    private final DaoConfig productResponseDaoConfig;
    private final DaoConfig loginResponseDaoConfig;
    private final DaoConfig breedsListDaoConfig;

    private final FarmMsgResponseDao farmMsgResponseDao;
    private final FarmSumDataDao farmSumDataDao;
    private final ProductResponseDao productResponseDao;
    private final LoginResponseDao loginResponseDao;
    private final BreedsListDao breedsListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        farmMsgResponseDaoConfig = daoConfigMap.get(FarmMsgResponseDao.class).clone();
        farmMsgResponseDaoConfig.initIdentityScope(type);

        farmSumDataDaoConfig = daoConfigMap.get(FarmSumDataDao.class).clone();
        farmSumDataDaoConfig.initIdentityScope(type);

        productResponseDaoConfig = daoConfigMap.get(ProductResponseDao.class).clone();
        productResponseDaoConfig.initIdentityScope(type);

        loginResponseDaoConfig = daoConfigMap.get(LoginResponseDao.class).clone();
        loginResponseDaoConfig.initIdentityScope(type);

        breedsListDaoConfig = daoConfigMap.get(BreedsListDao.class).clone();
        breedsListDaoConfig.initIdentityScope(type);

        farmMsgResponseDao = new FarmMsgResponseDao(farmMsgResponseDaoConfig, this);
        farmSumDataDao = new FarmSumDataDao(farmSumDataDaoConfig, this);
        productResponseDao = new ProductResponseDao(productResponseDaoConfig, this);
        loginResponseDao = new LoginResponseDao(loginResponseDaoConfig, this);
        breedsListDao = new BreedsListDao(breedsListDaoConfig, this);

        registerDao(FarmMsgResponse.class, farmMsgResponseDao);
        registerDao(FarmSumData.class, farmSumDataDao);
        registerDao(ProductResponse.class, productResponseDao);
        registerDao(LoginResponse.class, loginResponseDao);
        registerDao(BreedsList.class, breedsListDao);
    }
    
    public void clear() {
        farmMsgResponseDaoConfig.clearIdentityScope();
        farmSumDataDaoConfig.clearIdentityScope();
        productResponseDaoConfig.clearIdentityScope();
        loginResponseDaoConfig.clearIdentityScope();
        breedsListDaoConfig.clearIdentityScope();
    }

    public FarmMsgResponseDao getFarmMsgResponseDao() {
        return farmMsgResponseDao;
    }

    public FarmSumDataDao getFarmSumDataDao() {
        return farmSumDataDao;
    }

    public ProductResponseDao getProductResponseDao() {
        return productResponseDao;
    }

    public LoginResponseDao getLoginResponseDao() {
        return loginResponseDao;
    }

    public BreedsListDao getBreedsListDao() {
        return breedsListDao;
    }

}
