package com.lantian.lib_base.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lantian.lib_base.entity.module.response.userinfo.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, String> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property User_id = new Property(0, String.class, "user_id", true, "USER_ID");
        public final static Property State = new Property(1, String.class, "state", false, "STATE");
        public final static Property Username = new Property(2, String.class, "username", false, "USERNAME");
        public final static Property Password = new Property(3, String.class, "password", false, "PASSWORD");
        public final static Property Phone = new Property(4, String.class, "phone", false, "PHONE");
        public final static Property Email = new Property(5, String.class, "email", false, "EMAIL");
        public final static Property Nickname = new Property(6, String.class, "nickname", false, "NICKNAME");
        public final static Property Sex = new Property(7, String.class, "sex", false, "SEX");
        public final static Property Address = new Property(8, String.class, "address", false, "ADDRESS");
        public final static Property Id_card = new Property(9, String.class, "id_card", false, "ID_CARD");
        public final static Property Age = new Property(10, String.class, "age", false, "AGE");
        public final static Property Avatar = new Property(11, String.class, "avatar", false, "AVATAR");
        public final static Property Open_id = new Property(12, String.class, "open_id", false, "OPEN_ID");
        public final static Property User_api_key = new Property(13, String.class, "user_api_key", false, "USER_API_KEY");
        public final static Property Company_api_key = new Property(14, String.class, "company_api_key", false, "COMPANY_API_KEY");
        public final static Property Fial_time = new Property(15, String.class, "fial_time", false, "FIAL_TIME");
        public final static Property Is_admin = new Property(16, String.class, "is_admin", false, "IS_ADMIN");
        public final static Property Register_code = new Property(17, String.class, "register_code", false, "REGISTER_CODE");
        public final static Property Flag_code = new Property(18, String.class, "flag_code", false, "FLAG_CODE");
        public final static Property Last_code = new Property(19, String.class, "last_code", false, "LAST_CODE");
        public final static Property Smx_username = new Property(20, String.class, "smx_username", false, "SMX_USERNAME");
        public final static Property Smx_password = new Property(21, String.class, "smx_password", false, "SMX_PASSWORD");
        public final static Property Iot_username = new Property(22, String.class, "iot_username", false, "IOT_USERNAME");
        public final static Property Iot_password = new Property(23, String.class, "iot_password", false, "IOT_PASSWORD");
        public final static Property Appkey = new Property(24, String.class, "appkey", false, "APPKEY");
        public final static Property Appsecret = new Property(25, String.class, "appsecret", false, "APPSECRET");
        public final static Property Login_ip = new Property(26, String.class, "login_ip", false, "LOGIN_IP");
        public final static Property Created_at = new Property(27, String.class, "created_at", false, "CREATED_AT");
        public final static Property Updated_at = new Property(28, String.class, "updated_at", false, "UPDATED_AT");
        public final static Property Deleted_at = new Property(29, String.class, "deleted_at", false, "DELETED_AT");
        public final static Property Xian = new Property(30, String.class, "xian", false, "XIAN");
        public final static Property Shi = new Property(31, String.class, "shi", false, "SHI");
        public final static Property Sheng = new Property(32, String.class, "sheng", false, "SHENG");
        public final static Property Address_id = new Property(33, String.class, "address_id", false, "ADDRESS_ID");
        public final static Property Smx_id = new Property(34, String.class, "smx_id", false, "SMX_ID");
        public final static Property Smx_type = new Property(35, String.class, "smx_type", false, "SMX_TYPE");
        public final static Property Smx_ticket = new Property(36, String.class, "smx_ticket", false, "SMX_TICKET");
        public final static Property Usertype_id = new Property(37, String.class, "usertype_id", false, "USERTYPE_ID");
        public final static Property Lng = new Property(38, String.class, "lng", false, "LNG");
        public final static Property Lat = new Property(39, String.class, "lat", false, "LAT");
        public final static Property Updated_time = new Property(40, String.class, "updated_time", false, "UPDATED_TIME");
        public final static Property Staff_id = new Property(41, String.class, "staff_id", false, "STAFF_ID");
        public final static Property Name = new Property(42, String.class, "name", false, "NAME");
        public final static Property Addtime = new Property(43, String.class, "addtime", false, "ADDTIME");
        public final static Property Status = new Property(44, String.class, "status", false, "STATUS");
        public final static Property Syte_id = new Property(45, String.class, "syte_id", false, "SYTE_ID");
        public final static Property Shengdata = new Property(46, String.class, "shengdata", false, "SHENGDATA");
        public final static Property Shidata = new Property(47, String.class, "shidata", false, "SHIDATA");
        public final static Property Xiandata = new Property(48, String.class, "xiandata", false, "XIANDATA");
    }


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"USER_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: user_id
                "\"STATE\" TEXT," + // 1: state
                "\"USERNAME\" TEXT," + // 2: username
                "\"PASSWORD\" TEXT," + // 3: password
                "\"PHONE\" TEXT," + // 4: phone
                "\"EMAIL\" TEXT," + // 5: email
                "\"NICKNAME\" TEXT," + // 6: nickname
                "\"SEX\" TEXT," + // 7: sex
                "\"ADDRESS\" TEXT," + // 8: address
                "\"ID_CARD\" TEXT," + // 9: id_card
                "\"AGE\" TEXT," + // 10: age
                "\"AVATAR\" TEXT," + // 11: avatar
                "\"OPEN_ID\" TEXT," + // 12: open_id
                "\"USER_API_KEY\" TEXT," + // 13: user_api_key
                "\"COMPANY_API_KEY\" TEXT," + // 14: company_api_key
                "\"FIAL_TIME\" TEXT," + // 15: fial_time
                "\"IS_ADMIN\" TEXT," + // 16: is_admin
                "\"REGISTER_CODE\" TEXT," + // 17: register_code
                "\"FLAG_CODE\" TEXT," + // 18: flag_code
                "\"LAST_CODE\" TEXT," + // 19: last_code
                "\"SMX_USERNAME\" TEXT," + // 20: smx_username
                "\"SMX_PASSWORD\" TEXT," + // 21: smx_password
                "\"IOT_USERNAME\" TEXT," + // 22: iot_username
                "\"IOT_PASSWORD\" TEXT," + // 23: iot_password
                "\"APPKEY\" TEXT," + // 24: appkey
                "\"APPSECRET\" TEXT," + // 25: appsecret
                "\"LOGIN_IP\" TEXT," + // 26: login_ip
                "\"CREATED_AT\" TEXT," + // 27: created_at
                "\"UPDATED_AT\" TEXT," + // 28: updated_at
                "\"DELETED_AT\" TEXT," + // 29: deleted_at
                "\"XIAN\" TEXT," + // 30: xian
                "\"SHI\" TEXT," + // 31: shi
                "\"SHENG\" TEXT," + // 32: sheng
                "\"ADDRESS_ID\" TEXT," + // 33: address_id
                "\"SMX_ID\" TEXT," + // 34: smx_id
                "\"SMX_TYPE\" TEXT," + // 35: smx_type
                "\"SMX_TICKET\" TEXT," + // 36: smx_ticket
                "\"USERTYPE_ID\" TEXT," + // 37: usertype_id
                "\"LNG\" TEXT," + // 38: lng
                "\"LAT\" TEXT," + // 39: lat
                "\"UPDATED_TIME\" TEXT," + // 40: updated_time
                "\"STAFF_ID\" TEXT," + // 41: staff_id
                "\"NAME\" TEXT," + // 42: name
                "\"ADDTIME\" TEXT," + // 43: addtime
                "\"STATUS\" TEXT," + // 44: status
                "\"SYTE_ID\" TEXT," + // 45: syte_id
                "\"SHENGDATA\" TEXT," + // 46: shengdata
                "\"SHIDATA\" TEXT," + // 47: shidata
                "\"XIANDATA\" TEXT);"); // 48: xiandata
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(1, user_id);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(2, state);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(4, password);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(6, email);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(7, nickname);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(8, sex);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(9, address);
        }
 
        String id_card = entity.getId_card();
        if (id_card != null) {
            stmt.bindString(10, id_card);
        }
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(11, age);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(12, avatar);
        }
 
        String open_id = entity.getOpen_id();
        if (open_id != null) {
            stmt.bindString(13, open_id);
        }
 
        String user_api_key = entity.getUser_api_key();
        if (user_api_key != null) {
            stmt.bindString(14, user_api_key);
        }
 
        String company_api_key = entity.getCompany_api_key();
        if (company_api_key != null) {
            stmt.bindString(15, company_api_key);
        }
 
        String fial_time = entity.getFial_time();
        if (fial_time != null) {
            stmt.bindString(16, fial_time);
        }
 
        String is_admin = entity.getIs_admin();
        if (is_admin != null) {
            stmt.bindString(17, is_admin);
        }
 
        String register_code = entity.getRegister_code();
        if (register_code != null) {
            stmt.bindString(18, register_code);
        }
 
        String flag_code = entity.getFlag_code();
        if (flag_code != null) {
            stmt.bindString(19, flag_code);
        }
 
        String last_code = entity.getLast_code();
        if (last_code != null) {
            stmt.bindString(20, last_code);
        }
 
        String smx_username = entity.getSmx_username();
        if (smx_username != null) {
            stmt.bindString(21, smx_username);
        }
 
        String smx_password = entity.getSmx_password();
        if (smx_password != null) {
            stmt.bindString(22, smx_password);
        }
 
        String iot_username = entity.getIot_username();
        if (iot_username != null) {
            stmt.bindString(23, iot_username);
        }
 
        String iot_password = entity.getIot_password();
        if (iot_password != null) {
            stmt.bindString(24, iot_password);
        }
 
        String appkey = entity.getAppkey();
        if (appkey != null) {
            stmt.bindString(25, appkey);
        }
 
        String appsecret = entity.getAppsecret();
        if (appsecret != null) {
            stmt.bindString(26, appsecret);
        }
 
        String login_ip = entity.getLogin_ip();
        if (login_ip != null) {
            stmt.bindString(27, login_ip);
        }
 
        String created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindString(28, created_at);
        }
 
        String updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindString(29, updated_at);
        }
 
        String deleted_at = entity.getDeleted_at();
        if (deleted_at != null) {
            stmt.bindString(30, deleted_at);
        }
 
        String xian = entity.getXian();
        if (xian != null) {
            stmt.bindString(31, xian);
        }
 
        String shi = entity.getShi();
        if (shi != null) {
            stmt.bindString(32, shi);
        }
 
        String sheng = entity.getSheng();
        if (sheng != null) {
            stmt.bindString(33, sheng);
        }
 
        String address_id = entity.getAddress_id();
        if (address_id != null) {
            stmt.bindString(34, address_id);
        }
 
        String smx_id = entity.getSmx_id();
        if (smx_id != null) {
            stmt.bindString(35, smx_id);
        }
 
        String smx_type = entity.getSmx_type();
        if (smx_type != null) {
            stmt.bindString(36, smx_type);
        }
 
        String smx_ticket = entity.getSmx_ticket();
        if (smx_ticket != null) {
            stmt.bindString(37, smx_ticket);
        }
 
        String usertype_id = entity.getUsertype_id();
        if (usertype_id != null) {
            stmt.bindString(38, usertype_id);
        }
 
        String lng = entity.getLng();
        if (lng != null) {
            stmt.bindString(39, lng);
        }
 
        String lat = entity.getLat();
        if (lat != null) {
            stmt.bindString(40, lat);
        }
 
        String updated_time = entity.getUpdated_time();
        if (updated_time != null) {
            stmt.bindString(41, updated_time);
        }
 
        String staff_id = entity.getStaff_id();
        if (staff_id != null) {
            stmt.bindString(42, staff_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(43, name);
        }
 
        String addtime = entity.getAddtime();
        if (addtime != null) {
            stmt.bindString(44, addtime);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(45, status);
        }
 
        String syte_id = entity.getSyte_id();
        if (syte_id != null) {
            stmt.bindString(46, syte_id);
        }
 
        String shengdata = entity.getShengdata();
        if (shengdata != null) {
            stmt.bindString(47, shengdata);
        }
 
        String shidata = entity.getShidata();
        if (shidata != null) {
            stmt.bindString(48, shidata);
        }
 
        String xiandata = entity.getXiandata();
        if (xiandata != null) {
            stmt.bindString(49, xiandata);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(1, user_id);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(2, state);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(4, password);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(6, email);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(7, nickname);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(8, sex);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(9, address);
        }
 
        String id_card = entity.getId_card();
        if (id_card != null) {
            stmt.bindString(10, id_card);
        }
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(11, age);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(12, avatar);
        }
 
        String open_id = entity.getOpen_id();
        if (open_id != null) {
            stmt.bindString(13, open_id);
        }
 
        String user_api_key = entity.getUser_api_key();
        if (user_api_key != null) {
            stmt.bindString(14, user_api_key);
        }
 
        String company_api_key = entity.getCompany_api_key();
        if (company_api_key != null) {
            stmt.bindString(15, company_api_key);
        }
 
        String fial_time = entity.getFial_time();
        if (fial_time != null) {
            stmt.bindString(16, fial_time);
        }
 
        String is_admin = entity.getIs_admin();
        if (is_admin != null) {
            stmt.bindString(17, is_admin);
        }
 
        String register_code = entity.getRegister_code();
        if (register_code != null) {
            stmt.bindString(18, register_code);
        }
 
        String flag_code = entity.getFlag_code();
        if (flag_code != null) {
            stmt.bindString(19, flag_code);
        }
 
        String last_code = entity.getLast_code();
        if (last_code != null) {
            stmt.bindString(20, last_code);
        }
 
        String smx_username = entity.getSmx_username();
        if (smx_username != null) {
            stmt.bindString(21, smx_username);
        }
 
        String smx_password = entity.getSmx_password();
        if (smx_password != null) {
            stmt.bindString(22, smx_password);
        }
 
        String iot_username = entity.getIot_username();
        if (iot_username != null) {
            stmt.bindString(23, iot_username);
        }
 
        String iot_password = entity.getIot_password();
        if (iot_password != null) {
            stmt.bindString(24, iot_password);
        }
 
        String appkey = entity.getAppkey();
        if (appkey != null) {
            stmt.bindString(25, appkey);
        }
 
        String appsecret = entity.getAppsecret();
        if (appsecret != null) {
            stmt.bindString(26, appsecret);
        }
 
        String login_ip = entity.getLogin_ip();
        if (login_ip != null) {
            stmt.bindString(27, login_ip);
        }
 
        String created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindString(28, created_at);
        }
 
        String updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindString(29, updated_at);
        }
 
        String deleted_at = entity.getDeleted_at();
        if (deleted_at != null) {
            stmt.bindString(30, deleted_at);
        }
 
        String xian = entity.getXian();
        if (xian != null) {
            stmt.bindString(31, xian);
        }
 
        String shi = entity.getShi();
        if (shi != null) {
            stmt.bindString(32, shi);
        }
 
        String sheng = entity.getSheng();
        if (sheng != null) {
            stmt.bindString(33, sheng);
        }
 
        String address_id = entity.getAddress_id();
        if (address_id != null) {
            stmt.bindString(34, address_id);
        }
 
        String smx_id = entity.getSmx_id();
        if (smx_id != null) {
            stmt.bindString(35, smx_id);
        }
 
        String smx_type = entity.getSmx_type();
        if (smx_type != null) {
            stmt.bindString(36, smx_type);
        }
 
        String smx_ticket = entity.getSmx_ticket();
        if (smx_ticket != null) {
            stmt.bindString(37, smx_ticket);
        }
 
        String usertype_id = entity.getUsertype_id();
        if (usertype_id != null) {
            stmt.bindString(38, usertype_id);
        }
 
        String lng = entity.getLng();
        if (lng != null) {
            stmt.bindString(39, lng);
        }
 
        String lat = entity.getLat();
        if (lat != null) {
            stmt.bindString(40, lat);
        }
 
        String updated_time = entity.getUpdated_time();
        if (updated_time != null) {
            stmt.bindString(41, updated_time);
        }
 
        String staff_id = entity.getStaff_id();
        if (staff_id != null) {
            stmt.bindString(42, staff_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(43, name);
        }
 
        String addtime = entity.getAddtime();
        if (addtime != null) {
            stmt.bindString(44, addtime);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(45, status);
        }
 
        String syte_id = entity.getSyte_id();
        if (syte_id != null) {
            stmt.bindString(46, syte_id);
        }
 
        String shengdata = entity.getShengdata();
        if (shengdata != null) {
            stmt.bindString(47, shengdata);
        }
 
        String shidata = entity.getShidata();
        if (shidata != null) {
            stmt.bindString(48, shidata);
        }
 
        String xiandata = entity.getXiandata();
        if (xiandata != null) {
            stmt.bindString(49, xiandata);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // user_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // state
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // username
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // password
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // phone
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // email
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // nickname
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // sex
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // address
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // id_card
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // age
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // avatar
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // open_id
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // user_api_key
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // company_api_key
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // fial_time
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // is_admin
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // register_code
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // flag_code
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // last_code
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // smx_username
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // smx_password
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // iot_username
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // iot_password
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // appkey
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // appsecret
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // login_ip
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // created_at
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // updated_at
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // deleted_at
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // xian
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // shi
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // sheng
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // address_id
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // smx_id
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // smx_type
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // smx_ticket
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // usertype_id
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // lng
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // lat
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // updated_time
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // staff_id
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // name
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // addtime
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // status
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // syte_id
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // shengdata
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // shidata
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48) // xiandata
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setUser_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setState(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUsername(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPassword(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPhone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEmail(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setNickname(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSex(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAddress(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setId_card(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setAge(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAvatar(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setOpen_id(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setUser_api_key(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCompany_api_key(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setFial_time(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setIs_admin(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setRegister_code(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setFlag_code(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setLast_code(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setSmx_username(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setSmx_password(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setIot_username(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setIot_password(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setAppkey(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setAppsecret(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setLogin_ip(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setCreated_at(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setUpdated_at(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setDeleted_at(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setXian(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setShi(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setSheng(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setAddress_id(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setSmx_id(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setSmx_type(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setSmx_ticket(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setUsertype_id(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setLng(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setLat(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setUpdated_time(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setStaff_id(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setName(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setAddtime(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setStatus(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setSyte_id(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setShengdata(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setShidata(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setXiandata(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
     }
    
    @Override
    protected final String updateKeyAfterInsert(UserInfo entity, long rowId) {
        return entity.getUser_id();
    }
    
    @Override
    public String getKey(UserInfo entity) {
        if(entity != null) {
            return entity.getUser_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInfo entity) {
        return entity.getUser_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
