 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../../Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
#include "Java_com_lantian_lib_1lan_net_tcp_TCPServer_helloTCP.h"
/* Header for class com_lantian_lib_lan_net_tcp_TCPServer */

#ifndef _Included_com_lantian_lib_lan_net_tcp_TCPServer
#define _Included_com_lantian_lib_lan_net_tcp_TCPServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lantian_lib_lan_net_tcp_TCPServer
 * Method:    helloTCP
 * Signature: ()Ljava/lang/String;
 */
extern "C"
JNIEXPORT jstring  JNICALL Java_com_lantian_lib_1lan_net_tcp_TCPServer_helloTCP
  (JNIEnv * env, jclass TCPServer);

 extern "C"
 JNIEXPORT jint JNICALL Java_com_lantian_lib_1lan_net_tcp_TCPServer_helloInt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
 extern "C"
 JNIEXPORT jint