//
// Created by $SherlockHolmes on 2020/5/18.
//

#ifndef LT_SMART_PASTURE_JAVA_COM_LANTIAN_LIB_1LAN_NET_TCP_TCPSERVER_HELLOTCP_H
#define LT_SMART_PASTURE_JAVA_COM_LANTIAN_LIB_1LAN_NET_TCP_TCPSERVER_HELLOTCP_H


class Java_com_lantian_lib_1lan_net_tcp_TCPServer_helloTCP {

};


#endif //LT_SMART_PASTURE_JAVA_COM_LANTIAN_LIB_1LAN_NET_TCP_TCPSERVER_HELLOTCP_H
